import cadquery as cq
import math
#result = cq.Workplane("XY" ).box(3, 3, 0.5).edges("|Z").fillet(0.125)

#ARC FURNACE CAD AUTOMATIZATION

#TODO:

# CHAMBER PARAMETERS:
    

radial_flange_specs = [[["kf25","bulkhead"],3],[["kf40","bulkhead"],2]]
axial_flange_specs = [["kf40","bulkhead"],["kf25","bulkhead"]]


r_outer = 70
r_inner = 50
chamber_height = 100
model_height = 150
base_thickness = 10
bolt_dimensions = [5,30]
n_of_bolts = 20

#STOCK PARAMETERS:
bulkhead_thickness = 12.7

kf_bulkhead_bolt_ring_radii = {

    "kf16":19.5,
    "kf25":24,
    "kf40":31,
    "kf50":41.275,
}

kf_bulkhead_sizes = {
    
    "kf16":25.40,
    "kf25":30.15,
    "kf40":37.30,
    "kf50":47.40,
}


#WORK CONSTANTS:
kf_bulkhead_port_diameters= {
    "kf10":12,
    "kf16":17,
    "kf25":26,
    "kf40":41,
    "kf50":51
}

#DERIVED CONSTANTS:
    
baselid_thickness = (chamber_height-model_height)/2

#CODE: 


def get_standard_bolt_sizes(flange_name):

    bolt_diameter = None
    bolt_length = 10

    if flange_name[0:2].lower() == "kf":

        if flange_name[2:] in ["10","16","25"]:
            bolt_diameter = 4
        if flange_name[2:] in ["40","50"]:
            bolt_diameter = 5
    
    return [bolt_diameter,bolt_length]
            
        
def kf_port_flat_subtraction(name,workplane,surface_thickness):
    
    port = kf_bulkhead_port_diameters[name]
    bolt_ring = kf_bulkhead_bolt_ring_radii[name]
    bolt_diameter, bolt_length = get_standard_bolt_sizes(name)
    
    hole_negative = workplane.circle(port/2).extrude(surface_thickness)
    
    if surface_thickness >= 0:
        
        bolts_negative = workplane.polarArray(bolt_ring,0,360,6).circle(bolt_diameter/2).extrude(bolt_length)
    
    else:
        
        bolts_negative = workplane.polarArray(bolt_ring,0,360,6).circle(bolt_diameter/2).extrude(-bolt_length)
    
    return [hole_negative,bolts_negative]
    


def radial_flanges_setup(flange_array, r_outer, r_inner):

    
    #Making calculations necessary to determine optimal placement of ports
    total_flanges = 0
    total_port_size = 0
    
    port_design_params = []

    for entry in flange_array:
        
        if entry[0][1] == "bulkhead":
            port_param = []

            port_param.append(kf_bulkhead_port_diameters[entry[0][0]])
            port_param.append(entry[1])
            port_param.append(get_standard_bolt_sizes(entry[0][0]))
            port_param.append(kf_bulkhead_bolt_ring_radii[entry[0][0]])
            port_param.append(kf_bulkhead_sizes[entry[0][0]])

            total_port_size += port_param[4] * port_param[1]
            total_flanges += port_param[1]

            port_design_params.append(port_param)
    
    #Calculating optimal angular separation of ports and their cartesian coordinates
    
    pointer = 0
    flange_list = []
    
    for item in port_design_params:
        for i in range(item[1]):
            
            difference = (item[4]/total_port_size)*360
            pointer += difference
            
            flange_list.append([item[0],pointer-difference/2,item[2],item[3],item[4]]) #flange type, flange angle, bolt dimensions
    
    negatives = []
    
    for flange in flange_list:
        
        bolt_diameter = flange[2][0]
        bolt_length = flange[2][1]
        bolt_ring_radius = flange[3]
        bulkhead_sidelength = flange[4]*2

        #Solve math
        flange_port_rect = cq.Workplane("XZ").rect((bulkhead_sidelength),(bulkhead_sidelength)).extrude(-700)
        w_hole = flange_port_rect.faces("<Y").workplane().circle((flange[0])/2).extrude(r_outer-r_inner)
        w_threads = w_hole.faces("<Y").polarArray(bolt_ring_radius,0,360,6).circle(bolt_diameter/2).extrude(bolt_length)
        
        offset = r_outer*math.cos((math.acos(1-(((bulkhead_sidelength)**2)/(2*(r_outer**2)))))/2)
        
        w_threads = w_threads.rotate((0,0,0),(0,0,1),180).translate((0,-offset,0)).rotate((0,0,0),(0,0,1),flange[1])
        
        negatives.append(w_threads)
    
    #for negative in negatives:
        #show_object(negative)
    
    return negatives

def create_chamber_body(r_outer, r_inner, height, model_height, bolt_dimensions,n_of_bolts, radial_flange_specs):

    
    bolt_diameter = bolt_dimensions[0]
    bolt_length = bolt_dimensions[1]

    #Reference sketches
    outer_circle = cq.Workplane("XY").circle(r_outer)
    inner_circle = cq.Workplane("XY").circle(r_inner)
    concentric_circles = cq.Workplane("XY").circle(r_outer).circle(r_inner)
    
    #Creates physical body cylinder
    cylinder = concentric_circles.extrude(height)
    
    flange_negatives = radial_flanges_setup(radial_flange_specs, r_outer, r_inner)
    
    for negative in flange_negatives:
        #show_object(negative)
        cylinder = cylinder.cut(negative.translate((0,0,height/2)))

    baselid_thickness = (model_height-height)/2
    
    base = outer_circle.extrude(-baselid_thickness)
    lid = cq.Workplane("XY").workplane(offset=height).circle(r_outer).extrude(baselid_thickness)
    
    if axial_flange_specs:
        if len(axial_flange_specs) == 2:
            
            lid = lid.cut(kf_port_flat_subtraction(axial_flange_specs[0][0],cq.Workplane("XY").workplane(offset=(height+baselid_thickness)), -baselid_thickness)[0])
            lid = lid.cut(kf_port_flat_subtraction(axial_flange_specs[0][0],cq.Workplane("XY").workplane(offset=(height+baselid_thickness)), -baselid_thickness)[1])
            
            base = base.cut(kf_port_flat_subtraction(axial_flange_specs[1][0],cq.Workplane("XY").workplane(offset=(-baselid_thickness)), baselid_thickness)[0])
            base = base.cut(kf_port_flat_subtraction(axial_flange_specs[1][0],cq.Workplane("XY").workplane(offset=(-baselid_thickness)), baselid_thickness)[1])
            
            
            
        elif len(axial_flange_specs) == 1:

            lid = lid.cut(kf_port_flat_subtraction(axial_flange_specs[0][0],cq.Workplane("XY").workplane(offset=(height+baselid_thickness)), -baselid_thickness)[0])
            lid = lid.cut(kf_port_flat_subtraction(axial_flange_specs[0][0],cq.Workplane("XY").workplane(offset=(height+baselid_thickness)), -baselid_thickness)[1])
            
    

    show_object(cylinder)
    show_object(base)
    show_object(lid)


create_chamber_body(r_outer,r_inner,chamber_height,model_height,bolt_dimensions,n_of_bolts,radial_flange_specs)









